/*
  ESP32 program to collect energy data from PZEM-016 over Modbus
  and publish it to MQTT in a form acceptable to EmonCMS 
  i.e. "emon/ASHP/<subjectName>" (I use ASHP as my Node name in EmonCMS).

  Change Log:
  2024-08-05  Initial version with single JSON message
  2024-08-05  Revised for individual messages, one per Topic, and to use appropriate names
              for the topics, so they match my existing setup. That way I don't lose all
              my previous data when I have to reconfigure the Inputs/Feeds
  2025-03-12  Decided to switch to actually using this code, but modified to use HTTP interface because
              that's loads more reliable than MQTT and less grief... or so I thought!! Had to add URL encoding
              to the payload for both GET and POST, also some random 404s etc. from the EmonCMS instance
              Maybe MQTT is better?!
  2025-03-15  Added heap size logging 

*/

#include <Arduino.h>
#include <time.h>
#include <multi_heap.h>

#define MY_LOG_LEVEL ESP_LOG_DEBUG
#include <esp_log.h>  // have to include this manually

#define LOG_NAME "MyLog"

// Update these with values suitable for your network.

const char* ssid = "norcot";
const char* password = "nor265cot";
String URL = "http://emonpi.local/input/post";
//String URL = "http://emonpi.local/emoncms/input/post";
//String URL = "http://Macintosh-Gouk-New.local:8002/input/post";
const char* msgBody= "node=%node&fulljson=%json&apikey=%apiKey";
const char* nodeName = "ASHP";
const char* apiKey = "0e2988b2400a4ca9cb856015529de7f4";
const bool doHttpGet = true; // Controls use of GET vs POST...

String hostName;
IPAddress hostIp;
String uri;
uint16_t hostPort = 80;

/*
  Example HTTP GET
  GET:http://emonpi.local/input/post?node=mynode&fulljson={"power1":100,"power2":200,"power3":300}&apikey=fc9c9ae50942b35f8a1baa67649e301b

  Example HTTP POST
  URL: http://emonpi.local/input/post
  BODY: node=mynode&fulljson={"power1":100,"power2":200,"power3":300}&apikey=fc9c9ae50942b35f8a1baa67649e301b
*/

#include <ModbusRTUMaster.h>
#ifdef ESP8266
#include <ESP8266WiFi.h>
#include <SoftwareSerial.h>
#define SERIAL_CONFIG (SWSERIAL_8N1)
#define SERIAL_FLUSH_TX_ONLY // empty, as SoftwareSerial.flush() takes no parameter
#define MODBUS_RX D6
#define MODBUS_TX D7
SoftwareSerial modbusSerial(MODBUS_RX, MODBUS_TX);
ModbusRTUMaster modbus(modbusSerial);
#elif ESP32
#include <WiFi.h>
HardwareSerial modbusSerial(2);
ModbusRTUMaster modbus(modbusSerial);
#define SERIAL_CONFIG (SERIAL_8N1)
#define SERIAL_FLUSH_TX_ONLY false
#define MODBUS_RX 16
#define MODBUS_TX 17
#endif

#define MODBUS_SLAVE_ADDR 1
#define MODBUS_REG_START 0
#define MODBUS_REG_COUNT 9

//#include <resolveHostname.h>
#include <parseURL.h>

#include <HTTPClient.h>

WiFiClient espClient;

// I used these names because they matched the names from my previous energy monitor,
// and I didn't want to lose all the data I already had by using different ones
const char * valueNames[] = {
    "voltage",
    "current_b",
    "power_b",
    "energy_forward_b",
    "frequency",
    "power_factor_b"
};

// Don't use this other than to define how long the buffer needs to be!
struct energyData {
    int16_t voltage;
    int16_t current[2];
    int16_t power[2];
    int16_t energy[2];
    int16_t freq;
    int16_t pf;
};
// which is here
uint16_t dataBuf[sizeof(energyData)/2];

#define MAX_DATA_SIZE 250
char jsonbuff[MAX_DATA_SIZE] = "{\0";
#define MAX_VALUE_SIZE 50
char valueBuf[MAX_VALUE_SIZE] = "\0";

// NTP server to request epoch time
const char* ntpServer = "pool.ntp.org";

void setup_wifi() {

  delay(10);
  // We start by connecting to a WiFi network
  Serial.println();
  Serial.print("[setup_wifi] connecting to ");
  Serial.println(ssid);

  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  randomSeed(micros());

  Serial.println("");
  Serial.print("[setup_wifi] wifi connected: ");
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());
}

void startModbus() {
    modbus.begin(9600, SERIAL_CONFIG, MODBUS_RX, MODBUS_TX);
    modbus.setTimeout(200);
}

/*
  url_escape
  Uses URL-style escaping on whatever string it gets given, a JSON string in this instance
*/
String url_escape(String s){ // Translate payload to URL-encoded
  String value = "";
  for (int i=0;i<s.length();i++){
    if (isalpha(s[i]) || isdigit(s[i])){
      value = value + s[i];
    } else {
      int a = (unsigned char) s[i];
      String escaped = '%' + String(a, HEX);
      value = value + escaped;
    }
  }
  return value;
}

bool readModbusValues(){
  // Test data to check printf works
  uint16_t dummy = 0x0101;
  for (int i = 0; i < MODBUS_REG_COUNT; i++) {
    dataBuf[i] = dummy;
    dummy = dummy + 0x0101;
  }
  bool result = 0;
  result = modbus.readInputRegisters(MODBUS_SLAVE_ADDR, MODBUS_REG_START, dataBuf, MODBUS_REG_COUNT);
  /* */
  // Fake it out for now
  result = true;
  /* */
  if (result) {
    Serial.println("[readModbusValues] modbus read successful");
    Serial.print("[readModbusValues] hex: ");
    for (int i = 0; i < 8; i++)
    {
        Serial.printf(" 0x%04x ", dataBuf[i]);
    }
    Serial.println("");
    float values [6];
    /*
    values[0] = dataBuf[0] * 0.1;                           // Voltage(0.1V)
    values[1] = (dataBuf[1] + (dataBuf[2] << 16)) * 0.001;  // Current(0.001A)
    values[2] = (dataBuf[3] + (dataBuf[4] << 16)) * 0.1;    // Power(0.1W)
    values[3] = (dataBuf[5] + (dataBuf[6] << 16)) * 0.001;  // Energy(1Wh)
    values[4] = dataBuf[7] * 0.1;                           // Frequency
	  values[5] = dataBuf[8] * 0.01;							            // Power Factor
    */
    // Faking it
    values[0] = 249.1;                           // Voltage(0.1V)
    values[1] = 10.123;     // Current(0.001A)
    values[2] = 1234.1;     // Power(0.1W)
    values[3] = 3500.123;   // Energy(1Wh -> kWh)
    values[4] = 49.1;       // Frequency
	  values[5] = 93.1;       // Power Factor

    memset(jsonbuff, 0, MAX_DATA_SIZE);
    jsonbuff[0] = '{';
    Serial.print("[readModbusValues] values: ");
    for (int i = 0;i<6;i++){
      Serial.printf("%s:%f ", valueNames[i], values[i]);
      // Have to use URL encoding for the values
      snprintf(jsonbuff + strlen(jsonbuff), MAX_DATA_SIZE - strlen(jsonbuff), "\"%s\":%.3f,", valueNames[i], values[i]);
      //TEST snprintf(jsonbuff + strlen(jsonbuff), MAX_DATA_SIZE - strlen(jsonbuff), "%s:%.3f,", valueNames[i], values[i]);
      //TEST snprintf(jsonbuff + strlen(jsonbuff), MAX_DATA_SIZE - strlen(jsonbuff), "\"%s\":%.3f,", valueNames[i], values[i]);
      snprintf(valueBuf + strlen(valueBuf), MAX_VALUE_SIZE - strlen(valueBuf), "%.3f", values[i]);
      strcpy(valueBuf, "\0x");
    }
    jsonbuff[strlen(jsonbuff) - 1] = '}'; // Overwrite the last ","
    Serial.println("]");
    Serial.printf("[readModbusValues] JSON: %s\n", jsonbuff);
    String jsonString = jsonbuff;
    String urlJson = url_escape(jsonString);
    String payload(msgBody);  // It's ok to do this in a String because it gets binned after each function call
    payload.replace("%node", nodeName);
    payload.replace("%json", urlJson);
    payload.replace("%apiKey", apiKey);
    Serial.printf("[%s]\n", payload.c_str());
    int httpResult;
    HTTPClient httpClient;
    String action;
    if (doHttpGet){
      action = "GET";
      //String getURL = URL + "?" + payload;
      String getURL = uri + "?" + payload;
      Serial.printf("[HTTP] URL: %s\n", getURL.c_str());
      //httpClient.begin(URL);
      httpClient.begin(hostIp.toString(), hostPort, getURL);
      httpResult = httpClient.GET();
    } else{
      action = "POST";
      //Serial.printf("[HTTP] URL: %s\n", URL.c_str());
      Serial.printf("[HTTP] URL: %s\n", uri.c_str());
      const String headerName = "Content-Type";
      const String headerValue = "application/x-www-form-urlencoded";
      //httpClient.begin(URL);
      httpClient.begin(hostIp.toString(), hostPort, uri);
      httpClient.addHeader(headerName, headerValue, false, true);
      httpResult = httpClient.POST(payload);  
    }
    if (httpResult > 0) {
      String resultData = httpClient.getString();
      Serial.printf("[HTTP] Result: %s\n", resultData.c_str());
      if (httpResult == HTTP_CODE_OK){
        ;
      } else {
        Serial.printf("[HTTP] %s return code %d\n", action.c_str(), httpResult);
      }
    } else {
      Serial.printf("[HTTP] Error on %s call %d\n", action.c_str(), httpResult);
    }
    //httpClient.writeToStream(&Serial);  // Print the response body
    httpClient.end();

  } else {
    Serial.print("[readModbusValues] error reading modbus");
    if (modbus.getTimeoutFlag() == true) {
      Serial.print(": Timeout");
      modbus.clearTimeoutFlag();
    }
    else if (modbus.getExceptionResponse() != 0) {
      Serial.print(": Exception Response ");
      Serial.print(modbus.getExceptionResponse());
      switch (modbus.getExceptionResponse()) {
        case 1:
          Serial.print(" (Illegal Function)");
          break;
        case 2:
          Serial.print(" (Illegal Data Address)");
          break;
        case 3:
          Serial.print(" (Illegal Data Value)");
          break;
        case 4:
          Serial.print(" (Server Device Failure)");
          break;
        default:
          Serial.print(" (Uncommon Exception Response)");
          break;
      }
      modbus.clearExceptionResponse();
    }
    Serial.println();
  } 
  return result;

}


void setup() {
  delay(5000);
  Serial.begin(115200);
  esp_log_level_set(LOG_NAME, ESP_LOG_DEBUG);

  Serial.println("[setup] started");
  Serial.println("[setup] modbus starting");
  startModbus();
  Serial.println("[setup] modbus started");

  setup_wifi();
  
  bool result = parseURL(URL, hostName, hostIp, hostPort, uri);
  if (result) {
    Serial.printf("[setup] Host: Name: %s IP: %s Port: %d URI: %s\n", hostName.c_str(), hostIp.toString().c_str(), hostPort, uri.c_str());
  } else {
    Serial.printf("[setup] Can't resolve fucking URL % - going home\n", URL.c_str());
  }

  //         GMT_offset, DST_offset, server1...
  configTime(0, 0, ntpServer);

}

void reportHeap(int loc){
  multi_heap_info_t info;
  heap_caps_get_info(&info, MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT); // internal RAM, memory capable to store data or to create new task
  // total currently free in all non-continues blocks
  // minimum free ever
  // largest continues block to allocate big array
  Serial.printf("[heap %d] Total free:%d Min. free: %d Largest free block: %d\n", loc, 
                info.total_free_bytes, info.minimum_free_bytes, info.largest_free_block);
}

void loop() {
  reportHeap(1);
  bool result;
  Serial.println("[loop]");
  result = readModbusValues();
  reportHeap(2);
  Serial.flush();
  struct tm timeInfo;
  // configTime used GMT :-) so UTC is local time
  if (!getLocalTime(&timeInfo)) { 
      Serial.println("[loop] Failed to obtain time");
      return;
  }
  const size_t ISO_TIME_LEN = 21; // Include terminator
  char timeStr[ISO_TIME_LEN];
  strftime(timeStr, ISO_TIME_LEN, "%FT%TZ", &timeInfo);
  reportHeap(3);
  delay(10000);
}
